# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Uncomment this, if you're installing the VM locally
  #config.vm.box = "ubuntu/trusty64"
  config.vm.box = "dummy"

  config.vm.network "forwarded_port", guest: 443, host: 8080

  config.vm.synced_folder "./provisioning", "/provisioning", type: "rsync"

  config.vm.provision "shell", path: "provisioning/initial_setup.sh"

  config.vm.provider :aws do |aws, override|
    aws.ami = "ami-2d39803a"
    aws.instance_type = "t2.micro"
    aws.keypair_name = "adsa-workshops"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/adsa-workshops.pem"
  end
end
